services:
  - type: web
    name: demo-push-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
    healthCheckPath: /
